[package]
name = "normal-heights"
version = "0.1.0"
authors = ["Jon Olin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.1"
image = "0.23.7"
